spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/serverdb
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true